export const data = JSON.parse("{\"key\":\"v-3f3f1385\",\"path\":\"/posts/Tsukuba%20week07.html\",\"title\":\"筑波大學交換週記 Week 07\",\"lang\":\"en-US\",\"frontmatter\":{\"date\":\"2024-11-06T00:00:00.000Z\",\"category\":[\"Diary\"],\"tag\":[\"Diary\",\"University of Tsukuba\",\"Exchange Program\"],\"description\":\"筑波大學交換週記 Week 07 ZUTOMAYO! 來到日本之後第一個看到的演唱會訊息就是 ずっと真夜中でいいのに，明年有許多的演出可以期待。 為了要提早搶到票，買了一年的 Premium 會員資格，覺得也不會太貴就直接下手了。 除了訂了演唱會門票以外，就是會被各種周邊燒到w 然後就不小心買了新的專輯，是初回限定盤。 從下了訂單之後就在思考，既然買了專輯就會想要聽，但是現在手邊也沒有 CD 撥放器。 在 Amazon 和 メルカリ 上都逛了一下，後來選定了其中一個附音響的類型，而且 CD 讀取的部分是透明的，能看到 CD 轉動的樣子也覺得相當有趣。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/posts/Tsukuba%20week07.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Koios Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"筑波大學交換週記 Week 07\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"筑波大學交換週記 Week 07 ZUTOMAYO! 來到日本之後第一個看到的演唱會訊息就是 ずっと真夜中でいいのに，明年有許多的演出可以期待。 為了要提早搶到票，買了一年的 Premium 會員資格，覺得也不會太貴就直接下手了。 除了訂了演唱會門票以外，就是會被各種周邊燒到w 然後就不小心買了新的專輯，是初回限定盤。 從下了訂單之後就在思考，既然買了專輯就會想要聽，但是現在手邊也沒有 CD 撥放器。 在 Amazon 和 メルカリ 上都逛了一下，後來選定了其中一個附音響的類型，而且 CD 讀取的部分是透明的，能看到 CD 轉動的樣子也覺得相當有趣。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Diary\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"University of Tsukuba\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Exchange Program\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-11-06T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"筑波大學交換週記 Week 07\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-11-06T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"ZUTOMAYO!\",\"slug\":\"zutomayo\",\"link\":\"#zutomayo\",\"children\":[]},{\"level\":2,\"title\":\"學園祭 -  雙峰祭\",\"slug\":\"學園祭-雙峰祭\",\"link\":\"#學園祭-雙峰祭\",\"children\":[]},{\"level\":2,\"title\":\"文化季 - 工大祭\",\"slug\":\"文化季-工大祭\",\"link\":\"#文化季-工大祭\",\"children\":[]},{\"level\":2,\"title\":\"回台灣\",\"slug\":\"回台灣\",\"link\":\"#回台灣\",\"children\":[]},{\"level\":2,\"title\":\"後記\",\"slug\":\"後記\",\"link\":\"#後記\",\"children\":[]}],\"readingTime\":{\"minutes\":9.51,\"words\":2854},\"filePathRelative\":\"posts/Tsukuba week07.md\",\"localizedDate\":\"November 6, 2024\",\"excerpt\":\"<h1> 筑波大學交換週記 Week 07</h1>\\n<h2> ZUTOMAYO!</h2>\\n<p>來到日本之後第一個看到的演唱會訊息就是 ずっと真夜中でいいのに，明年有許多的演出可以期待。</p>\\n<p>為了要提早搶到票，買了一年的 Premium 會員資格，覺得也不會太貴就直接下手了。</p>\\n<p>除了訂了演唱會門票以外，就是會被各種周邊燒到w</p>\\n<p>然後就不小心買了新的專輯，是初回限定盤。</p>\\n<p>從下了訂單之後就在思考，既然買了專輯就會想要聽，但是現在手邊也沒有 CD 撥放器。</p>\\n<p>在 Amazon 和 メルカリ 上都逛了一下，後來選定了其中一個附音響的類型，而且 CD 讀取的部分是透明的，能看到 CD 轉動的樣子也覺得相當有趣。</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
