export const data = JSON.parse("{\"key\":\"v-42a8c4c3\",\"path\":\"/posts/Tsukuba%20week09.html\",\"title\":\"筑波大學交換週記 Week 09\",\"lang\":\"en-US\",\"frontmatter\":{\"date\":\"2024-11-21T00:00:00.000Z\",\"category\":[\"Diary\"],\"tag\":[\"Diary\",\"University of Tsukuba\",\"Exchange Program\"],\"description\":\"筑波大學交換週記 Week 09 因為感冒，中間有兩天左右的時間請了假在家好好休息，也有了可以放心說服自己好好睡覺的理由。 好在症狀並不嚴重，雖然中間因為出現肌肉痠痛而懷疑是否確診，但在快篩過後也確定了只是單純感冒。 因為感冒而缺的課，再加上回台灣期間的請假，中間有些需要補回來的進度。對於邊交換邊推甄的我來說，這學期能不能把學分拿滿是相當重要的關鍵，也因此有些微的不安。 在前幾篇也許我有提到，這邊的課程難度並不高，而更偏向於通識課，也並沒有實作。相對的，作業以及考試的比重就會比較重一些。 目前有修的專業課程\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/KoiosBlog/posts/Tsukuba%20week09.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Koios Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"筑波大學交換週記 Week 09\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"筑波大學交換週記 Week 09 因為感冒，中間有兩天左右的時間請了假在家好好休息，也有了可以放心說服自己好好睡覺的理由。 好在症狀並不嚴重，雖然中間因為出現肌肉痠痛而懷疑是否確診，但在快篩過後也確定了只是單純感冒。 因為感冒而缺的課，再加上回台灣期間的請假，中間有些需要補回來的進度。對於邊交換邊推甄的我來說，這學期能不能把學分拿滿是相當重要的關鍵，也因此有些微的不安。 在前幾篇也許我有提到，這邊的課程難度並不高，而更偏向於通識課，也並沒有實作。相對的，作業以及考試的比重就會比較重一些。 目前有修的專業課程\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Diary\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"University of Tsukuba\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Exchange Program\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-11-21T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"筑波大學交換週記 Week 09\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-11-21T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"秋..冬\",\"slug\":\"秋-冬\",\"link\":\"#秋-冬\",\"children\":[]},{\"level\":2,\"title\":\"財務管理\",\"slug\":\"財務管理\",\"link\":\"#財務管理\",\"children\":[]},{\"level\":2,\"title\":\"推甄放榜\",\"slug\":\"推甄放榜\",\"link\":\"#推甄放榜\",\"children\":[]},{\"level\":2,\"title\":\"後記\",\"slug\":\"後記\",\"link\":\"#後記\",\"children\":[]}],\"readingTime\":{\"minutes\":11.2,\"words\":3361},\"filePathRelative\":\"posts/Tsukuba week09.md\",\"localizedDate\":\"November 21, 2024\",\"excerpt\":\"<h1> 筑波大學交換週記 Week 09</h1>\\n<p>因為感冒，中間有兩天左右的時間請了假在家好好休息，也有了可以放心說服自己好好睡覺的理由。</p>\\n<p>好在症狀並不嚴重，雖然中間因為出現肌肉痠痛而懷疑是否確診，但在快篩過後也確定了只是單純感冒。</p>\\n<p>因為感冒而缺的課，再加上回台灣期間的請假，中間有些需要補回來的進度。對於邊交換邊推甄的我來說，這學期能不能把學分拿滿是相當重要的關鍵，也因此有些微的不安。</p>\\n<p>在前幾篇也許我有提到，這邊的課程難度並不高，而更偏向於通識課，也並沒有實作。相對的，作業以及考試的比重就會比較重一些。</p>\\n<p>目前有修的專業課程</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
