export const data = JSON.parse("{\"key\":\"v-3d8a3ae6\",\"path\":\"/posts/Tsukuba%20week06.html\",\"title\":\"筑波大學交換週記 Week 06\",\"lang\":\"en-US\",\"frontmatter\":{\"date\":\"2024-10-29T00:00:00.000Z\",\"category\":[\"Diary\"],\"tag\":[\"Diary\",\"University of Tsukuba\",\"Exchange Program\"],\"description\":\"筑波大學交換週記 Week 06 日常與非日常、 在日本已經過了一段時間，漸漸地也找到一個穩定的生活型態。我想這件事情對我來說並不是困難的，單純在一個環境當中製作出一種習慣，依循著它，形成一種日常。 這件事情我想尤其在有外在的規範存在的時候尤其簡單。 既然是在學校當中，就會存在課表。無論課表上的課程是不是自己喜歡的、是不是真的自己想要選的。一旦這個課表決定了，接下來數個月的生活軌跡就會一定程度的穩定。跟隨著這樣的軌跡，按表操課，就能夠形成一個學生的日常。 與在台灣不同的，也許比較多在於生活。最主要還是在吃，與在清大的期間不太一樣，花了不少的時間在處理午餐或是晚餐，也會因為要準備食材開始比較常去超市等等。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/posts/Tsukuba%20week06.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Koios Blog\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"筑波大學交換週記 Week 06\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"筑波大學交換週記 Week 06 日常與非日常、 在日本已經過了一段時間，漸漸地也找到一個穩定的生活型態。我想這件事情對我來說並不是困難的，單純在一個環境當中製作出一種習慣，依循著它，形成一種日常。 這件事情我想尤其在有外在的規範存在的時候尤其簡單。 既然是在學校當中，就會存在課表。無論課表上的課程是不是自己喜歡的、是不是真的自己想要選的。一旦這個課表決定了，接下來數個月的生活軌跡就會一定程度的穩定。跟隨著這樣的軌跡，按表操課，就能夠形成一個學生的日常。 與在台灣不同的，也許比較多在於生活。最主要還是在吃，與在清大的期間不太一樣，花了不少的時間在處理午餐或是晚餐，也會因為要準備食材開始比較常去超市等等。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Diary\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"University of Tsukuba\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Exchange Program\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-10-29T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"筑波大學交換週記 Week 06\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-10-29T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"日常與非日常、\",\"slug\":\"日常與非日常、\",\"link\":\"#日常與非日常、\",\"children\":[]},{\"level\":2,\"title\":\"想要怎樣生活著?\",\"slug\":\"想要怎樣生活著\",\"link\":\"#想要怎樣生活著\",\"children\":[]},{\"level\":2,\"title\":\"JAXA\",\"slug\":\"jaxa\",\"link\":\"#jaxa\",\"children\":[]},{\"level\":2,\"title\":\"後記\",\"slug\":\"後記\",\"link\":\"#後記\",\"children\":[]}],\"readingTime\":{\"minutes\":7.36,\"words\":2209},\"filePathRelative\":\"posts/Tsukuba week06.md\",\"localizedDate\":\"October 29, 2024\",\"excerpt\":\"<h1> 筑波大學交換週記 Week 06</h1>\\n<h2> 日常與非日常、</h2>\\n<p>在日本已經過了一段時間，漸漸地也找到一個穩定的生活型態。我想這件事情對我來說並不是困難的，單純在一個環境當中製作出一種習慣，依循著它，形成一種日常。</p>\\n<p>這件事情我想尤其在有外在的規範存在的時候尤其簡單。</p>\\n<p>既然是在學校當中，就會存在課表。無論課表上的課程是不是自己喜歡的、是不是真的自己想要選的。一旦這個課表決定了，接下來數個月的生活軌跡就會一定程度的穩定。跟隨著這樣的軌跡，按表操課，就能夠形成一個學生的日常。</p>\\n<p>與在台灣不同的，也許比較多在於生活。最主要還是在吃，與在清大的期間不太一樣，花了不少的時間在處理午餐或是晚餐，也會因為要準備食材開始比較常去超市等等。</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
